version: '3'

services:
  api:
    build: ./simple_api
    container_name: student-api
    ports:
      - "5000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - student_network

  website:
    image: php:apache
    container_name: student_website
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=root
      - PASSWORD=root
    depends_on:
      - api
    ports:
      - "8080:80"  # Mappez le port 80 du conteneur sur le port 8080 de l'hôte
    networks:
      - student_network

networks:
  student_network: